Added MoveCommand and RotateCommand
Fantast03/ooaip2223 pull request #3
Opened 2022-11-17 12:31 UTC by Fantast03

Added MoveCommand and RotateCommand, written all necessary interfaces, Commands fully covered by tests.

2022-11-18 02:41 UTC, zaryanezrya requested changes

2022-11-18 02:41 UTC, zaryanezrya commented on Dockerfile
> +FROM mcr.microsoft.com/dotnet/sdk:6.0-alpine as build
Убрать

2022-11-18 02:41 UTC, zaryanezrya commented on src/SpaceBattle/Entities/MoveCommand.cs
> +        if (movable == null || movable.Position == null || movable.MoveSpeed == null ||
Детали реализации сложения

2022-12-08 10:07 UTC, Fantast03 commented on Dockerfile
> +FROM mcr.microsoft.com/dotnet/sdk:6.0-alpine as build
В Dockerfile были внесены стейджы с дев окружением, тестированием и генераций ковередж репортов, все содержание было удалено за ненадобностью.

2022-12-08 10:09 UTC, Fantast03 commented on src/SpaceBattle/Entities/MoveCommand.cs
> +        if (movable == null || movable.Position == null || movable.MoveSpeed == null ||
Операция сложения теперь инъектируется через IoC контейнер

2022-12-16 02:48 UTC, zaryanezrya approved these changes

2022-12-16 02:48 UTC, merged